# URL redirects (.ie)
server {
    listen 80;
    server_name crm.metachannelcorp.ie crm.metachannelcorporation.ie crm.metachannelcorporation.com;

    return 301 http://crm.metachannelcorp.com$request_uri;
}

# Main server (Odoo)
server {
    listen 80;
    server_name crm.metachannelcorp.com;

    location / {
        proxy_pass http://odoo:8069;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 720s;
        proxy_connect_timeout 720s;
        proxy_send_timeout 720s;
    }
}
